about/urls.py
from django.urls import path
from . import views
from django.shortcuts import redirect
from django.urls import reverse

def temp (request):
    return redirect(reverse('site:about'))

app_name='site'
urlpatterns= [
        path('',temp,name='temp'),
        path('about',views.about, name='about'),
        path('Details/',views.work, name='work'),
        path('blog/',views.blog,name='blog'),
        path('projectResearch/',views.accounting,name='accounting')
        ]

django_service/urls.py
# Nice help on urls https://stackoverflow.com/questions/52473830/unable-to-resolve-url-string-for-path-using-name-with-reverse/52473895

from django.contrib import admin
from django.urls import include, path 
from django.shortcuts import redirect
from django.urls import reverse
from django.http import HttpResponse

'''
def temp (request):
    return redirect(reverse('site:about'))
'''

urlpatterns = [
        path('s/', include('shorts.urls')),
        path('downloads/',include('shorts.urls_downloads')),
        path('', include('about.urls')),
        path('resume/', include('resume.urls'), name='resume'),
        #path('admin/', admin.site.urls),
        #path('',temp, name = "temp"),
]

resume/urls.py
from django.urls import path
from . import views

app_name='resume'
urlpatterns= [
        path('',views.index, name='index')
        ]

shorts/urls.py
from django.urls import path
from django.shortcuts import redirect
from django.urls import reverse
from . import views

def temp (request):
    return redirect('shorts:r1')

app_name='shorts'

urlpatterns= [
        path('',temp,name='temp'),
        path('moody',views.moodyresume, name='r1'),
        path('resume',views.moodyresume, name='r2'),
        path('evernote',views.oauth_evernote,name='evernote'),
        ]

resume/models.py
from django.db import models

# Create your models here.

shorts/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .apps import AboutConfig

# Create your views here.
def about(request):
    return render(request,f'{AboutConfig.name}/about.html')

def work(request):
    return render(request,f'{AboutConfig.name}/work.html')

def blog(request):
    return render(request,f'{AboutConfig.name}/blog.html')

def accounting(request):
    return render(request,f'{AboutConfig.name}/accounting.html')

resume/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .apps import WebAppConfig
# Create your views here.

def index(request):
    context = {"hello":"The title of the mind map"}
    return render(request,f'{WebAppConfig.name}/index.html',context)

shorts/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse

# Create your views here.

def moodyresume(request):
    return redirect('https://drive.google.com/file/d/1hd6g-Gqq_Pbh6DHSnWaALmpKZOH2RFuR/view?usp=sharing')

def maruti1resume(request):
    return redirect('https://drive.google.com/file/d/1jEL6oFntTa-ZJTSwJrW9ip1i34cUKDNt/view?usp=sharing')

def maruti2resume(request):
    return redirect('https://drive.google.com/file/d/1DTzDzSMY4RKc1_2iQRTbgd0YMD1oeMKh/view?usp=sharing')

def oauth_evernote(request):
    result=request.GET #result is QueryDict (class in Django) object 
    oauth=result.get('oauth_token','None')
    verifier=result.get('oauth_verifier','None')
    return HttpResponse(
        f'oauth_token:{oauth} <br> verifier:{verifier}')

def resumePdf(request):
    return redirect('https://drive.google.com/file/d/14QtY5MXR33lGyJHpuOVbacdZd0Q_kmPs/view?usp=sharing')

def resumeRahul(request):
    return redirect("https://drive.google.com/file/d/18iqmQeJC-KJZ_e4dVau9wg6pDr8EYv_P/view?usp=sharing")

about/templates/about/about.html
{% extends "about/layout.html" %}
{% load static %}

{% block content %}
<!-- site-content -->
<div class="site-content">
    <article class="page">
        <div class="page-content">
            <div class="pretty-links">
                <div class="lead lead-about">
                    <p>I am passionate about using statistics and 
                    machine learning in the field of investment research.
                    </p>
                </div>
            </div>
            <figure class="site-profile">
                <img  class='imgProfile' src="{% static '/about/img/photo.jpg' %}">
            </figure>
            <p>My name is Rahul Indhane, I am a data scientist and a full stack developer. I am  interested in making essentially reliable decisions through algorithms in domain of finance.</p> 
        </div>
    </article>
</div>
<!-- site-content -->
{% endblock %}

about/templates/about/accounting.html
{% extends "about/layout.html" %}
{% load static %}

{% block content %}
<!-- site-content -->
<div class="site_content">
    <h1 class="page__title">
        <span class="page__title-pre">Project Details</span> 
        <span>Accounting Research </span>
    </h1>

    <br/>
    <section class="notelist" >
        <article class="notelist__item">
            <time class="notelist__date" datetime="2021-06-15T00:00:00Z">15 June 2021</time>
            <div class="notelist__content">
                <p> Dear Reader, <br> I am seeking to carry out a capstone project for my accounting research course. It is an mandatory requirement in the credit course of my post graduate diploma. Check out the curriculum details <a href='https://amityonline.com/i-learn/post-graduate-diploma-in-public-accounting-online' target='_blank' rel="noopener noreferrer" >here</a>.</p>
                <p>
                    Applicable area for project work are : 
                    <ul>
                        <li>Accounting Methodology</li>
                        <li>Business Finance</li>
                        <li>Economic Analysis</li>
                        <li>Portfolio Management </li>
                    </ul>
                </p>
                <p>
                    If you or your organization need to conduct a research work, related to above topics, please reach out to me on this email: <a href="mailto:email@irahul.me"> email@irahul.me</a>.     
                </p>
                <p>
                 Outcome of project work will have following deliverables <span> can be fine tuned as per requirement </span>:
                 <ol>
	                <li> Comprehensive project report prepared as per APA style guidelines <a href='https://apastyle.apa.org/' target='_blank' rel="noopener noreferrer"> Link</a> </li> 
	                <li>Full copyrights to source code </li>
	                <li>Access to catalogued data gathered for research</li>
	                <li>Author-credit to involved stakeholders</li>
	                <li>Hosting and Publishing to desired web platform for access to third parties</li>
                </ol>
                </p>
            </div>
        </article>
        <article class="notelist__item">
            <time class="notelist__date" datetime="2021-06-16T00:00:00Z">16 June 2021</time>
            <div class="notelist__content">
                <p>Info:</p>
                <p> One of the key requirement for project completion is to carry out the complete work under a project guide.He needs to certify that the conduct of the project-work has been under his supervision. Eligibility criteria for project guide:
                 <ul>
                     <li>must have a Post Graduate degree </li>
                     <li>minimum 10 years of work experience</li>
                 </ul> 
                </p>
                <p> The overall project guidelines are available in this <a id ='guidelines' href='https://drive.google.com/file/d/14Ms1wHQ3AwQkIyJtJpiqnOOLxUOrSdrT/view?usp=sharing'>document</a>  
                </p>
            </div>
        </article>
    </section>
</div>
 <!-- site-content -->
{% endblock %}

about/templates/about/blog.html
{% extends "about/layout.html" %}
{% load static %}

{% block content %}
<!-- site-content -->
<article class="page">  
    <header class="page-header">
      <h1 class="page-title">Blog Details</h1>
    </header>
    <div class="page-content">
        <div class="pretty-links">
            <div class="lead lead-about">
                <p>Read about my exploration & understanding of <a href="https://rindhane.github.io/">machine learning</a>.
                </p>
            </div>
        </div>
    </div>
</article>
<!-- site-content -->
{% endblock %}

about/templates/about/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Common metas -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex">
    <meta name="googlebot" content="noindex">
    <title>
    Rahul | About Me
    </title>
    {% load static %}
    <!-- SEO metas -->
    <meta name="description" content="About me">
    <link rel="canonical" href="https://irahul.me/">
    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/assets/img/apple-touch-icon.png">
    <link rel="shortcut icon" href="/assets/img/favicon.ico">
    <!-- CSS files -->
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Lora:400,400i,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'about/css/style.css' %}">
  
</head>  
<body>
    <div class="site">
        <!-- site-header start-->
        <header class="site-header">
            <nav class="site-nav">
                <a href="{% url 'site:about' %}" title="Home page">About</a>
                <a href="{% url 'site:work' %}" title="Details about Work">Work</a>
                <a href="{% url 'site:blog'%}" title="My blog">Blog</a>
            </nav>
        </header>
        <!-- site-header end -->
        {% block content %}{% endblock %}
        <!---site-footer start-->
        <footer class="site-footer">
            <div class="site-copy">© 2021<span class="site-author">Rahul Indhane</span></div>
            <div class="site-links">
                <div class="site-contact">
                    <ul>
                        <li><a href="mailto:email@irahul.me">Contact</a></li>
                        <li><a target="_blank" rel="external" href="https://github.com/rindhane/">Github</a></li>
                        <li><a target="_blank" rel="external" href="https://twitter.com/i_rahul01">Twitter</a></li>
                    </ul>
                </div>
                <div class="site-source">
                    <ul>
                    <li><a target="_blank" href="https://github.com/rindhane/data_blog">Source</a></li>
                    <span><a href="https://github.com/clenemt/jackal">Theme</a></span>
                    <li><a target="_blank" href="https://github.com/christophM/christophm.github.io">credits</a>
                    </li>
                    </ul>
                </div>
            </div>
        </footer>
        <!-- site-footer end -->  
    </div>
</body>
</html>

about/templates/about/work.html
{% extends "about/layout.html" %}
{% load static %}

{% block content %}
<!-- site-content -->
<div class="site_content">
    <h1 class="page__title">
        <span class="page__title-pre">Quick overview</span> 
        <span>Current & Past Work </span>
    </h1>
    <br/>
    <section class="projectlist" >
        <article class="projectlist__item">
            <h2 class="projectlist__title">
                <a class="projectlist__link" href="{% url 'site:accounting' %}">Project: Accounting Research</a>
            </h2>
            <div class="projectlist__meta">
                <time class="projectlist__date" datetime="2021-05-18T00:00:00Z">May 2021 </time>
                <span class="tags">
                    <a href="#" class="tag">Research</a>
                    <a href="#" class="tag">Current</a>
                </span>
            </div>
            <p class="projectlist__excerpt">On account of my curriculum's requirement, I am looking to conduct a project work related to portfolio research </p>
            <p>
                <a href="{% url 'site:accounting' %}">Read →</a>
            </p>
        </article>
        <article class="projectlist__item">
            <h2 class="projectlist__title">
                <a class="projectlist__link" href="{% url 'resume:index'%}">Curriculum Vitae</a>
            </h2>
            <div class="projectlist__meta">
                <time class="projectlist__date" datetime="2021-01-18T00:00:00Z">Jan 2021 </time>
                <span class="tags"><a href="#" class="tag">Past Work</a></span>
            </div>
            <p class="projectlist__excerpt">Detailed overview of my past projects and work experience. </p>
            <p>
                <a href="{% url 'resume:index'%}">Read →</a>
            </p>
        </article>
    </section>
</div>
 <!-- site-content -->
{% endblock %}

resume/templates/resume/index.html
<!doctype html><html lang="en"><head>{% load static %}<meta charset="utf-8"/><link rel="icon" href="{% static '/resume/favicon.ico' %}"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="robots" content="noindex"><meta name="googlebot" content="noindex"><meta name="Rahul Resume" content="Resume of Rahul"/><link rel="apple-touch-icon" href="{% static '/resume/logo192.png' %}"/><link rel="manifest" href="{% static '/manifest.json' %}"/><title>@iRahul</title><script defer="defer" src="/static/js/main.af66e973.js"></script><link href="/static/css/main.c292fe84.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>

templates/dashboard.html
{%extends 'layout.html' %}

{%block body %}
    <h1>Dashboard <small> Welcome {{session.username}}</small></h1>
    <a class="btn btn-success" href="/add_article">Add Articles</a>
    <hr>
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Author</th>
            <th>Date</th>
            <th></th>
            <th></th>
        </tr>
        {% for article in articles %}
        <tr>
            <td>{{article.id}}</td>
            <td>{{article.title}}</td>
            <td>{{article.author}}</td>
            <td>{{article.create_date}}</td>
            <td><a href ="edit_article/{{article.id}}" class="btn btn-default float-sm-right">Edit</a></td>
            <td>
                <form action="{{url_for('delete_article',idx=article.id)}}" method ="POST">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="submit" value="Delete" class="btn btn-danger">
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
{%endblock%}